#!/bin/bash
rm -rf _build
make html

pushd _build/html
git init
git config user.name 'Autodoc'
git config user.email '<>'
git add .
git commit -m "Autogenerated documentation"
git push --force --quiet "https://${GH_TOKEN}@github.com/b1naryth1ef/disco" master:gh-pages
popd
